### ISSUE TITLE
Create docker image

### ISSUE THREAD

**Issue by tkqubo** [tkqubo/codeclimate-tslint#1]

**Comment by mrb** [comment]
@tkqubo Hey there! I'd be happy to help out if you need assistance - shoot me an email mrb@codeclimate.com

**Comment by tkqubo** [comment]
@mrb Thanks so much!  Although I cannot spare too much time to develop recently, I will constantly and gradually develop this repo :smile:

**Comment by johnapost** [comment]
I'm really looking forward to this engine!

**Comment by tkqubo** [comment]
@mrb Hi, I think I have prepared all the stuffs required for Code Climate engine.  Is that OK?

**Comment by mrb** [comment]
@tkqubo Yes! Shoot me an email so we can coordinate

**Comment by KillaPL** [comment]
@tkqubo @tkqubo Any success with that? I'd love to use tslint with code climate.

**Comment by kyleholzinger** [comment]
@tkqubo @mrb any progress on this? It'd be awesome to get a docker image up there so we could at least run this locally

**Comment by tkqubo** [comment]
At least it worked on my Mac with some minor configuration (but sorry I couldn't setup CentOS environment).  Could you try the latest commit and see if it works? @mrb

**Comment by tkqubo** [comment]
I believe we are already able to create a runnable docker image, so I'll close this issue 😃

**Comment by kyleholzinger** [comment]
🎉

**Comment by kyleholzinger** [comment]
For anyone trying this themselves, run the following within this repo:
```bash
docker build -t codeclimate/codeclimate-tslint .
```

And then you can use `codeclimate analyze --dev` in whatever ts repo you want
