### ISSUE TITLE
Installation via the Code Climate CLI fails

### ISSUE THREAD

**Issue by KimBurgess** [tkqubo/codeclimate-tslint#24]
When attempting to install the engine locally, installation fails during the docker image pull.

```
$ CODECLIMATE_DEBUG=1 codeclimate engines:install 
Pulling docker images.
FATA[0003] Error response from daemon: manifest for codeclimate/codeclimate-tslint:latest not found 
error: (CC::CLI::Engines::Install::ImagePullFailure) unable to pull image codeclimate/codeclimate-tslint
[DEBUG] backtrace: /usr/src/app/lib/cc/cli/engines/install.rb:35:in `pull_engine_image'
	/usr/src/app/lib/cc/cli/engines/install.rb:22:in `block (2 levels) in pull_docker_images'
	/usr/src/app/lib/cc/cli/engines/install.rb:22:in `each'
	/usr/src/app/lib/cc/cli/engines/install.rb:22:in `block in pull_docker_images'
	/usr/src/app/lib/cc/cli/engines/install.rb:19:in `each'
	/usr/src/app/lib/cc/cli/engines/install.rb:19:in `pull_docker_images'
	/usr/src/app/lib/cc/cli/engines/install.rb:13:in `run'
	/usr/src/app/lib/cc/cli/command.rb:73:in `execute'
	/usr/src/app/lib/cc/cli/runner.rb:26:in `run'
	/usr/src/app/lib/cc/cli/runner.rb:9:in `run'
	/usr/src/app/bin/codeclimate:6:in `<main>'
```

Currently, Docker Hub does not have a image that's been tagged as `latest` and it appears the CLI is attempting to pull this, despite the "beta" channel setting in the `.codeclimate.yml`.

I'm new to the Code Climate ecosystem so unsure if this is an issue on their CLI side, or how this engine is currently distributed.

As a workaround, pulling the beta image manually then locally tagging as latest works.

**Comment by maxjacobson** [comment]
Hi @KimBurgess. Sorry about that, and good catch. This will be fixed in the next version of the CLI https://github.com/codeclimate/codeclimate/issues/647

**Comment by maxjacobson** [comment]
This is released
