### ISSUE TITLE
add support for tslint-ionic-rules

### ISSUE THREAD

**Issue by naerion89** [tkqubo/codeclimate-tslint#33]
Hi,

I have the same issue  as #26 
I wouldlike to use the ionic tslint rules (https://github.com/ionic-team/tslint-ionic-rules)
Can you give me a solution for using ionic rules or add support for it ?

Regards,
Gaetan BOGAERT

**Comment by naerion89** [comment]
up ?

**Comment by naerion89** [comment]
up ??

**Comment by tkqubo** [comment]
Sorry not yet...!

**Comment by naerion89** [comment]
tks for you answer !
