### ISSUE TITLE
Update tslint-react package

### ISSUE THREAD

**Issue by ridgekimani** [tkqubo/codeclimate-tslint#38]
I have added react related rules and I got an error from the tslint package
<img width="818" alt="screen shot 2018-01-08 at 5 13 14 pm" src="https://user-images.githubusercontent.com/15478648/34674990-1a56bc92-f499-11e7-8b8b-30e6a9b350c5.png">
Please updated the [tslint-react](https://www.npmjs.com/package/tslint-react) package to the latest build.

**Comment by tkqubo** [comment]
Hi, I've just updated all the NPM modules.  Could you try it again with the newest one?  @ridgekimani

**Comment by ridgekimani** [comment]
Am still getting the same issue when I use 'tslint-react' in the extends identifier @tkqubo

**Comment by tkqubo** [comment]
I see.  So the version is not a cause...  Is there any public repo with the same issue?

**Comment by ridgekimani** [comment]
Not really.. But when I remove the the 'tslint-react` it works like a charm

**Comment by tkqubo** [comment]
Hi, I have made changes to codeclimate-tslint again.  Could you try it with tslint-react? @ridgekimani
