### ISSUE TITLE
tsd is Deprecated, Switch to Typings

### ISSUE THREAD

**Issue by darthtrevino** [tkqubo/codeclimate-tslint#5]

**Comment by tkqubo** [comment]
@darthtrevino Thanks for your advice, I switched from tsd to typings.

One thing I couldn't resolve is:

https://github.com/tkqubo/codeclimate-tslint/blob/fc3f1d3ff717953867a2f191a5b4dae67e14f0b7/src/index.ts#L26-L28

I don't know how to get the type information of `rx.Observable.fromNodeCallback` correctly, so I simply gave up by casting `rx.Observable` to `any`...

**Comment by darthtrevino** [comment]
That was quick! Thanks, @tkqubo 

FWIW, I wouldn't sweat that line too much.

**Comment by abey-alex** [comment]
Any update on this?

**Comment by amcdnl** [comment]
FYI - I did this already https://github.com/swimlane/codeclimate-tslint
