### ISSUE TITLE
Request: add `tslint-microsoft-contrib`

### ISSUE THREAD

**Issue by eelco** [tkqubo/codeclimate-tslint#55]
We use a bunch of the linting rules from that [package](https://www.npmjs.com/package/tslint-microsoft-contrib), it’s quite popular (almost ~200K downloads in the previous week, according to npmjs.com).

**Comment by BBosman** [comment]
I got pointed to this issue by Code Climate Support as we’re using that ruleset as well, so I’d like to +1 this request.

**Comment by ssube** [comment]
Support just pointed me to this repo as well, the microsoft-contrib rules (along with sonarts and others) would be a great help for my projects.

**Comment by tkqubo** [comment]
I simply added tslint-microsoft-contrib in package.json.  If there is any problem, please open a new issue.  Thanks @eelco
