### ISSUE TITLE
errors on numeric separator

### ISSUE THREAD

**Issue by ssube** [tkqubo/codeclimate-tslint#57]
The version of tslint being run in this engine [seems to have trouble parsing Typescript's numeric separators](https://codeclimate.com/github/ssube/isolex/test/utils/TestPicklist.ts/source#issue-cbcfe2741de39d26b8566e96c526ff93):

![underscore separator splits numeric literal](https://user-images.githubusercontent.com/451959/50848237-557f9900-1339-11e9-8301-e1338adf2d30.png)

This looks to be a version issue, as [the build output](https://codeclimate.com/github/ssube/isolex/builds/343) shows a few rules being skipped:

> Could not find implementations for the following rules specified in the configuration:
>
>    increment-decrement
>    no-default-import
>    unnecessary-constructor
>
> Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
> If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.

I contacted support and they pointed me to this repo. Are there any plans to update tslint and support these language features/rules?

**Comment by tkqubo** [comment]
I have updated TypeScript from `2.6.2` to `3.3.3333` (not the latest `3.4.0` since Angular currently doesn't support it).  Please check if errors are removed @ssube.  Sorry for my late response.

**Comment by tkqubo** [comment]
I believe the issue has been fixed.  I will close this.
