### ISSUE TITLE
Update tslint plugins

### ISSUE THREAD

**Issue by vicrep** [tkqubo/codeclimate-tslint#58]
Hi,

Noticed that quite a few plugins were significantly out of date, which is making the engine behave differently than expected.

Notably:
- tslint-config-prettier:  1.6.0 -> 1.17.0
- tslint-plugin-prettier: 1.3.0 -> 2.0.1
- tslint-react: 3.4.0 -> 3.6.0

Would it be possible to update them please?

Also, have you considered using an automatic dep manager for those kind of repetitive tasks? (e.g. https://renovatebot.com/ , https://greenkeeper.io/)

**Comment by piotrb** [comment]
Also I'd like to see the tslint engine itself be updated, its quite a bit behind now and breaks on modern typescript syntax.

**Comment by tkqubo** [comment]
For today's commits, I believe these modules are properly updated.  Sorry for the delay, and I will close this issue as fixed.
