### ISSUE TITLE
Support tslint-react-hooks plugin

### ISSUE THREAD

**Issue by jonahwh** [tkqubo/codeclimate-tslint#61]
We have support for `tslint-react`, but it would be super cool to also support [`tslint-react-hooks`](https://github.com/Gelio/tslint-react-hooks) :)

**Comment by sombreroEnPuntas** [comment]
Was this issue solved?

I'm getting an error when running the gitlab docker image for `codeclimate` when I enable this plugin:
```
Status: Downloaded newer image for codeclimate/codeclimate-tslint:latest
/usr/src/app/node_modules/tslint/lib/configuration.js:57
        throw new error_1.FatalError("Failed to load " + configPath + ": " + error.message, error);
        ^

FatalError: Failed to load /tmp/codeclimate-tslint/36d76f73a3b0fc690a96d6fa1e61b106a8896a5d161c2793102b8f7d78dd0f55.json: Invalid "extends" configuration value - could not require "tslint-react-hooks". Review the Node lookup algorithm (https://nodejs.org/api/modules.html#modules_all_together) for the approximate method TSLint uses to find the referenced configuration file.
```

**Comment by jonahwh** [comment]
Sorry, should have indicated why I closed this. 

We switched to eslint, which has typescript support, and is [the way of the future](https://medium.com/palantir/tslint-in-2019-1a144c2317a9). 

See also https://github.com/codeclimate/codeclimate-eslint/pull/447#issuecomment-490654267

**Comment by sombreroEnPuntas** [comment]
Oh, so then it means that if I extend my tslint with `"tslint-react-hooks"` I can no longer use this plugin?

**Comment by jonahwh** [comment]
Yeah. The docker image doesn't know about that dependency. Feel free to open a new issue and reference this one if you need to keep using tslint and want the react hooks plugin added to the codeclimate image. I'm gonna leave this closed just cause our solution was to switch to eslint. :)

**Comment by sombreroEnPuntas** [comment]
I would consider it a breaking change, to drop tslint plugins support when they are not **yet** legacy.
But ok, got the message. Use eslint instead.

Cheers!
